-- MySQL Script generated by MySQL Workbench
-- Thu Jun 15 15:44:36 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_recipe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_recipe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_recipe` DEFAULT CHARACTER SET utf8mb3 ;
USE `db_recipe` ;


-- -----------------------------------------------------
-- Table `db_recipe`.`dish`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `db_recipe`.`dish` (
	`id` INT auto_increment NOT NULL,
	`name` varchar(100) NOT NULL,
	`ingredient` LONGTEXT NOT NULL,
	`recipe_step` LONGTEXT NOT NULL,
	`time` VARCHAR(100) NOT NULL,
	`serving` varchar(100) NOT NULL,
	`image` varchar(250) NOT NULL,
	CONSTRAINT dish_pk PRIMARY KEY (id),
	CONSTRAINT dish_FK FOREIGN KEY (id) REFERENCES db_recipe.category(id),
	CONSTRAINT dish_FK_1 FOREIGN KEY (id) REFERENCES db_recipe.`dish`(id),
	CONSTRAINT dish_FK_2 FOREIGN KEY (id) REFERENCES db_recipe.`day`(id)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_recipe`.`dish`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `db_recipe`.`dish` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL,
  `birthday` DATETIME DEFAULT NULL,
   CONSTRAINT dish_pk PRIMARY KEY (`id`)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_recipe`.`category`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `db_recipe`.`category` (
	` id`  INT auto_increment NOT NULL,
    `name` varchar(100) NOT NULL,
	CONSTRAINT category_pk PRIMARY KEY (`id`)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;



-- -----------------------------------------------------
-- Table `db_recipe`.`day`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `db_recipe`.`day` (
	` id`  INT auto_increment NOT NULL,
	`date` TIME NOT NULL,
	`type` enum('matin','midi','soir') DEFAULT 'midi' NOT NULL,
	CONSTRAINT day_pk PRIMARY KEY (`id`)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;










